sudo: true
dist: xenial

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/kubeplay:latest images/kubeplay
      - docker images
      - docker push $DOCKER_USERNAME/kubeplay:latest
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/kubeplay:latest
